version: '3.5'
services:
  mysql:
    image: hub.c.163.com/library/mysql:5.7
    restart: always
    container_name: "dubbo_project_mysql"
    expose:
      - 3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      #- ./conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
      - ./doc/initdb.d:/docker-entrypoint-initdb.d
    networks:
      default:
       ipv4_address: 172.30.1.200
networks:
    default:
      external:
        name: app-network
